name: ya_finance_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  go_router: ^15.2.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  fuzzywuzzy: ^1.2.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.34
  shared_preferences: ^2.5.3
  shake: ^3.0.0
  get_it: ^8.0.3
  fl_chart: ^1.0.0
  worker_manager: ^7.2.6
  flutter_colorpicker: ^1.1.0
  pin_code_fields: ^8.0.1
  local_auth: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1
  mocktail: ^1.0.0
  golden_toolkit: ^0.15.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - lib/assets/icons/articles.svg
    - lib/assets/icons/bank_account.svg
    - lib/assets/icons/expenses.svg
    - lib/assets/icons/income.svg
    - lib/assets/icons/settings.svg
    - lib/assets/icons/transac_history.svg
    - lib/assets/icons/analysis.svg
    - lib/assets/icons/back.svg
    - lib/assets/icons/account_edit.svg